version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /stuff-web-app.js
    destination: /var/www/html/
hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: root
